[project]
name = "amech"
version = "0.1.0"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge", "auto-mech"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
numpy = ">=1.26.4,<1.27"
scipy = ">=1.13.0,<1.14"
xarray = ">=2024.5.0,<2024.6"
more-itertools = ">=10.2.0,<10.3"
pyyaml = ">=6.0.1,<6.1"
mako = ">=1.3.5,<1.4"
networkx = ">=3.3,<4"
matplotlib = ">=3.8.4,<3.9"
pytest = ">=8.2.0,<8.3"
pytest-cov = ">=5.0.0,<5.1"
future = ">=1.0.0,<1.1"
ruff = ">=0.4.4,<0.5"
pylint = ">=3.2.0,<3.3"
nglview = ">=3.1.2,<3.2"
cantera = ">=3.0.0,<3.1"
rdkit = ">=2024.3.2,<2024.4"
qcelemental = ">=0.27.1,<0.28"
py3dmol = ">=2.1.0,<2.2"
python-igraph = ">=0.11.5,<0.12"
projrot = ">=1.7.2,<1.8"
pac99 = ">=1.5.0,<1.6"
thermp = ">=0.6.1,<0.7"
