[project]
name = "amech-dev"
version = "2024.6.19"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge", "auto-mech"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
# Dev dependencies
pip = ">=24.0,<25"
pylint = ">=3.2.3,<3.3"
pytest = ">=8.2.2,<8.3"
pre-commit = ">=3.7.1,<3.8"
black = ">=24.4.2,<24.5"
ruff = ">=0.5.0,<0.6"
mypy = ">=1.10.1,<1.11"
sphinx = ">=7.3.7,<7.4"
myst-parser = ">=3.0.1,<3.1"
# AutoChem dependencies
ipython = ">=8.25.0,<8.26"
ipywidgets = ">=8.1.3,<8.2"
jupyter = ">=1.0.0,<1.1"
more-itertools = ">=10.3.0,<10.4"
networkx = ">=3.3,<4"
numpy = ">=1.26,<2"
py3dmol = ">=2.1.0,<2.2"
pyparsing = ">=3.1.2,<3.2"
pyyaml = ">=6.0.1,<6.1"
qcelemental = ">=0.27.1,<0.28"
rdkit = ">=2024.3.3,<2024.4"
scipy = ">=1.13.1,<1.14"
xarray = ">=2024.6.0,<2024.7"
# AutoIO dependencies
mako = ">=1.3.5,<1.4"
# AutoFile dependencies
# MechAnalyzer dependencies
click = ">=8.1.7,<8.2"
matplotlib = ">=3.8.4,<3.9"
python-igraph = ">=0.11.5,<0.12"
# Compiled AutoMech modules
automech-toolbox = ">=2024.6.19"

[system-requirements]
linux="3.10"
