[project]
name = "amech-dev"
version = "2024.6.19"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge", "auto-mech"]
platforms = ["linux-64"]

[tasks]
build = { cmd = "./scripts/build.sh", cwd = "." }
build-toolbox = { cmd = "./src/automech-toolbox/build.sh", cwd = "." }
download = { cmd = "./scripts/download.sh", cwd = "." }
install = { cmd = "./scripts/install.sh", cwd = "." }
update = { cmd = "./scripts/update.sh", cwd = "." }
git = { cmd = "./scripts/git.sh", cwd = "." }
test = { cmd = "./scripts/test.py", cwd = "." }
subtasks = { cmd = "./scripts/subtasks.sh" }
node = { cmd = "./scripts/node.sh" }
x2z = { cmd = "./scripts/x2z.py" }

[dependencies]
python = "3.10.*"
# AutoChem dependencies
ipython = ">=8.25.0,<8.26"
ipywidgets = ">=8.1.3,<8.2"
jupyter = ">=1.0.0,<1.1"
more-itertools = ">=10.3.0,<10.4"
networkx = ">=3.3,<4"
numpy = ">=1.26,<2"
py3dmol = ">=2.1.0,<2.2"
pyparsing = ">=3.1.2,<3.2"
pyyaml = ">=6.0.1,<6.1"
qcelemental = ">=0.27.1,<0.28"
rdkit = ">=2024.3.3,<2024.4"
scipy = ">=1.13.1,<1.14"
xarray = ">=2024.6.0,<2024.7"
# AutoIO dependencies
mako = ">=1.3.5,<1.4"
# AutoFile dependencies
# MechAnalyzer dependencies
click = ">=8.1.7,<8.2"
matplotlib = ">=3.8.4,<3.9"
python-igraph = ">=0.11.5,<0.12"
# Compiled AutoMech modules
automech-toolbox = ">=2024.6.19"
parallel = ">=20240722"

[system-requirements]
linux="3.10"
libc = { family="glibc", version="2.17" }

# Dev dependencies
[pypi-dependencies]
pip = "*"
pylint = "*"
pytest = "*"
pre-commit = "*"
black = "*"
ruff = "*"
mypy = "*"
sphinx = "*"
myst-parser = "*"
sphinx-book-theme = "*"
sphinx-autodoc-typehints = "*"

[feature.build.dependencies]
cmake = ">=3.30.0,<3.31"
cxx-compiler = ">=1.7.0,<1.8"
fortran-compiler = ">=1.7.0,<1.8"
c-compiler = ">=1.7.0,<1.8"
make = ">=4.3,<5"
rattler-build = ">=0.18.1,<0.19"
libgfortran = ">=3.0.0,<3.1"
libgcc = ">=7.2.0,<7.3"
libstdcxx-ng = ">=14.1.0,<14.2"

[environments]
build = ["build"]
