package:
  name: automech
  version: "2024.7.18"

about:
  license: MIT
  description: Automated workflow routines for calculating theoretical data for reaction mechanisms
  repository: https://github.com/Auto-Mech/mechdriver

source:
  path: ..

build:
  noarch: python
  script:
    # AutoMech-Toolbox
    - mkdir -p ${PREFIX}/bin
    - mkdir -p ${PREFIX}/share
    - cp ${RECIPE_DIR}/../src/automech-toolbox/static/bin/* ${PREFIX}/bin/.
    - cp -r ${RECIPE_DIR}/../src/automech-toolbox/static/bin/* ${PREFIX}/share/.
    # AutoChem
    - pip install ${RECIPE_DIR}/../src/autochem -v --no-deps
    # AutoIO
    - pip install ${RECIPE_DIR}/../src/autoio -v --no-deps
    # AutoFile
    - pip install ${RECIPE_DIR}/../src/autofile -v --no-deps
    # MechAnalyzer
    - pip install ${RECIPE_DIR}/../src/mechanalyzer -v --no-deps
    # MechDriver
    - pip install ${RECIPE_DIR}/../src/mechdriver -v --no-deps

requirements:
  host:
    - pip
    - python >=3.10
    - poetry
    - wheel
  run:
    - python >=3.10
    # AutoChem dependencies
    - ipython >=8.25.0,<8.26
    - ipywidgets >=8.1.3,<8.2
    - jupyter >=1.0.0,<1.1
    - more-itertools >=10.3.0,<10.4
    - networkx >=3.3,<4
    - numpy >=1.26,<2
    - py3dmol >=2.1.0,<2.2
    - pylint >=3.2.3,<3.3
    - pyparsing >=3.1.2,<3.2
    - pytest >=8.2.2,<8.3
    - pyyaml >=6.0.1,<6.1
    - qcelemental >=0.27.1,<0.28
    - rdkit >=2024.3.3,<2024.4
    - scipy >=1.13.1,<1.14
    - xarray >=2024.6.0,<2024.7
    # AutoIO dependencies
    - mako >=1.3.5,<1.4
    # AutoFile dependencies
    # MechAnalyzer dependencies
    - click >=8.1.7,<8.2
    - matplotlib >=3.8.4,<3.9
    - python-igraph >=0.11.5,<0.12
